### ISSUE TITLE
Create Channel-HLF2.5.9

### ISSUE THREAD

**Issue by YoungHypo** [hyperledger/cello#639]
According to [Create a channel(latest)](https://hyperledger-fabric.readthedocs.io/en/latest/create_channel/create_channel_participation.html), **Differences between HLF2.5.9 and older version:**
1. system channels are no longer supported, replaced by application channels.
2. block creation of system channel is no longer needed before ordering node creation.

**Channel Creation Process:**
Step1: Update orderer.yaml
- [x] Modify the configuration of orderer to turn off the system channel. #637 
- General.BootstrapMethod-none
- ChannelParticipation.Enabled-ture
- Admin related parameter configuration

Step2: Generate the channel's genesis block
- [x] configtxgen: a tool to build blocks by reading channel configuration files. #636 
- [x] configtx.yaml: channel configuration, mainly consists of three parts: Organizaions, Orderer, Profiles. #640 

Step3: Osnadmin CLi add orderer to channel
- [x] #638 

Step4: Add peer to channel
- [x] #638  

Step5: Set anchor peer
- [x] In process

**Comment by yeasy** [comment]
[v2.5.10](https://github.com/hyperledger/fabric/releases/tag/v2.5.10) is the latest 2.5 LTS.
We can use the version 2.5 LTS for safe.
